services:
  db:
    image: mysql:8.0.42-debian
    container_name: post_db
    restart: always
    volumes: 
      - ./msql_data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10   
  redis:
    image: redis:7.4.4-alpine
    container_name: 'post_redis'
    restart: always
    ports:
      - "6379:6379"
    volumes: 
      - ./cache:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]