"""add delivery cost

Revision ID: 27b66f17f44e
Revises: 83c18910865b
Create Date: 2025-07-04 13:26:59.566238

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "27b66f17f44e"
down_revision: Union[str, Sequence[str], None] = "83c18910865b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("parcels", sa.Column("delivery_cost", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("parcels", "delivery_cost")
    # ### end Alembic commands ###
